# Generated by Django 4.0 on 2024-04-28 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to=''),
        ),
    ]
