# Generated by Django 5.0.4 on 2024-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_bookreview_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to=''),
        ),
    ]
